//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accountable.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accountable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string administrator {
            get {
                return ResourceManager.GetString("administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emboss.
        /// </summary>
        internal static string emboss {
            get {
                return ResourceManager.GetString("emboss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Administrator.
        /// </summary>
        internal static string employee_admin {
            get {
                return ResourceManager.GetString("employee_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Administrator.
        /// </summary>
        internal static string factory_admin {
            get {
                return ResourceManager.GetString("factory_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Employee.
        /// </summary>
        internal static string factory_emp {
            get {
                return ResourceManager.GetString("factory_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foil &amp; Emboss.
        /// </summary>
        internal static string foil_emboss {
            get {
                return ResourceManager.GetString("foil_emboss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foil Print.
        /// </summary>
        internal static string foil_print {
            get {
                return ResourceManager.GetString("foil_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Employee.
        /// </summary>
        internal static string marketing_emp {
            get {
                return ResourceManager.GetString("marketing_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Employee.
        /// </summary>
        internal static string office_emp {
            get {
                return ResourceManager.GetString("office_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Print.
        /// </summary>
        internal static string offset_print {
            get {
                return ResourceManager.GetString("offset_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Administrator.
        /// </summary>
        internal static string root_admin {
            get {
                return ResourceManager.GetString("root_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Spot.
        /// </summary>
        internal static string security_spot {
            get {
                return ResourceManager.GetString("security_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV Coating.
        /// </summary>
        internal static string uv_coating {
            get {
                return ResourceManager.GetString("uv_coating", resourceCulture);
            }
        }
    }
}
